export const productCatalog = [
  {
    name: "Ultra 100",
    slug: "ultra-100",
    category: "rayos-x",
    audience: "humano",
    format: "portatil",
  },
  {
    name: "Sistema Portatil Digital Ultra 100 + Flat Panel",
    slug: "sistema-portatil-digital-ultra-100-flat-panel",
    category: "rayos-x",
    audience: "humano",
    format: "portatil",
  },
  {
    name: "HF 525 Plus",
    slug: "hf-525-plus",
    category: "rayos-x",
    audience: "humano",
    format: "fijo",
    image: "/imgs/equipments/h525plus.jpg",
    featured: true,
  },
  {
    name: "HF-525 Plus Digital",
    slug: "hf-525-plus-digital",
    category: "rayos-x",
    audience: "humano",
    format: "fijo",
  },
  {
    name: "XFM",
    slug: "xfm",
    category: "rayos-x",
    audience: "humano",
    format: "movil",
  },
  {
    name: "Unidad Movil Digital HF-525 Plus",
    slug: "unidad-movil-digital-hf-525-plus",
    category: "rayos-x",
    audience: "humano",
    format: "movil",
  },
  {
    name: "Ultra 100 Vet",
    slug: "ultra-100-vet",
    category: "rayos-x",
    audience: "veterinario",
    format: "portatil",
  },
  {
    name: "Sistema de Rayos X Digital",
    slug: "sistema-de-rayos-x-digital",
    category: "rayos-x",
    audience: "veterinario",
    format: "portatil",
  },
  {
    name: "SonoScape E1 EXP",
    slug: "sonoscape-e1-exp",
    category: "ecografia",
    audience: "humano",
    format: "portatil",
  },
  {
    name: "SonoScape E2",
    slug: "sonoscape-e2",
    category: "ecografia",
    audience: "humano",
    format: "portatil",
  },
  {
    name: "SonoScape X3",
    slug: "sonoscape-x3",
    category: "ecografia",
    audience: "humano",
    format: "portatil",
  },
  {
    name: "SonoScape X5",
    slug: "sonoscape-x5",
    category: "ecografia",
    audience: "humano",
    format: "portatil",
  },
  {
    name: "SonoScape S8 EXP",
    slug: "sonoscape-s8-exp",
    category: "ecografia",
    audience: "humano",
    format: "portatil",
  },
  {
    name: "SonoScape S9",
    slug: "sonoscape-s9",
    category: "ecografia",
    audience: "humano",
    format: "portatil",
  },
  {
    name: "SonoScape X11",
    slug: "sonoscape-x11",
    category: "ecografia",
    audience: "humano",
    format: "portatil",
  },
  {
    name: "SonoScape P9 Elite",
    slug: "sonoscape-p9-elite",
    category: "ecografia",
    audience: "humano",
    format: "estacionario",
    image: "/imgs/equipments/p9elite.jpg",
    featured: true,
  },
  {
    name: "SonoScape P12 Elite",
    slug: "sonoscape-p12-elite",
    category: "ecografia",
    audience: "humano",
    format: "estacionario",
  },
  {
    name: "SonoScape P40 Elite",
    slug: "sonoscape-p40-elite",
    category: "ecografia",
    audience: "humano",
    format: "estacionario",
  },
  {
    name: "SonoScape P60",
    slug: "sonoscape-p60",
    category: "ecografia",
    audience: "humano",
    format: "estacionario",
  },
  {
    name: "SonoScape E1 EXP Vet",
    slug: "sonoscape-e1-exp-vet",
    category: "ecografia",
    audience: "veterinario",
    format: "portatil",
  },
  {
    name: "SonoScape X3 Vet",
    slug: "sonoscape-x3-vet",
    category: "ecografia",
    audience: "veterinario",
    format: "portatil",
  },
  {
    name: "SonoScape X5 Vet",
    slug: "sonoscape-x5-vet",
    category: "ecografia",
    audience: "veterinario",
    format: "portatil",
  },
  {
    name: "SonoScape ProPet 60",
    slug: "sonoscape-propet-60",
    category: "ecografia",
    audience: "veterinario",
    format: "estacionario",
    image: "/imgs/equipments/propet60.jpg",
    featured: true,
  },
  {
    name: "Flat Panel LG Black 14x17",
    slug: "flat-panel-lg-black-14x17",
    category: "digitalizacion",
    audience: "general",
    format: "detector",
    image: "/imgs/equipments/flatpanel.jpg",
    featured: true,
  },
  {
    name: "Flat Panel LG Black 17x17",
    slug: "flat-panel-lg-black-17x17",
    category: "digitalizacion",
    audience: "general",
    format: "detector",
  },
  {
    name: "I-MAX PRO",
    slug: "i-max-pro",
    category: "dental",
    audience: "general",
    format: "panoramico",
  },
  {
    name: "I-MAX CEPH PRO",
    slug: "i-max-ceph-pro",
    category: "dental",
    audience: "general",
    format: "panoramico",
  },
  {
    name: "I-MAX 3D XPRO",
    slug: "i-max-3d-xpro",
    category: "dental",
    audience: "general",
    format: "cone-beam",
  },
  {
    name: "I-MAX 3D CEPH XPRO",
    slug: "i-max-3d-ceph-xpro",
    category: "dental",
    audience: "general",
    format: "cone-beam",
  },
  {
    name: "GARION",
    slug: "garion",
    category: "fluoroscopia",
    audience: "general",
    format: "arco-en-c",
  },
  {
    name: "CARMEX RK FP",
    slug: "carmex-rk-fp",
    category: "fluoroscopia",
    audience: "general",
    format: "arco-en-c",
  },
  {
    name: "PRIMUS",
    slug: "primus",
    category: "densitometria",
    audience: "general",
    format: "dxa",
    featured: true,
    image: "/imgs/equipments/primus.jpg",
  },
];
